# This is a basic workflow to help you get started with Actions

name: DeployWebsite

# Controls when the workflow will run
on:
  # Triggers the workflow on push but only for the deploy branch
  push:
    branches: [ deploy ]
  # pull_request:
  #   branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ftp.jsontoolsplus.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./jsontoolsplus-nextjs
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          README.md
          installGitHooks.js
          LICENSE
          .git**
          .es**